app/controllers/comments_controller.rb, app/controllers/image_results_controller.rb, app/controllers/posts_controller.rb, test/controllers/comments_controller_test.rb, test/controllers/image_results_controller_test.rb, test/controllers/posts_controller_test.rb
=> added controllers

app/models/comment.rb, app/models/image_result.rb, app/models/post.rb, app/models/user.rb, db/migrate/20230522085047_add_age_to_user.rb, db/schema.rb
=> added all teh validations and associations

config/routes.rb
the routes all work; verified yesterday with sarah and this morning I tested them out a bit
=> finished routes

app/controllers/posts_controller.rb, config/routes.rb
I also changed the comments routes to not include show and index (sincce we will use the post controller to have the indexs and there wont be a show)
=> added the skeleton for the post controller

app/controllers/posts_controller.rb, app/policies/post_policy.rb, app/views/posts/index.html.erb, app/views/posts/new.html.erb
just the new/create form view is done
=> the form works

app/controllers/posts_controller.rb, app/views/comments/index.html.erb, app/views/comments/new.html.erb, app/views/comments/show.html.erb, app/views/posts/index.html.erb, app/views/posts/show.html.erb
the basic stuff is there but it wasnt tested bc of the pundit errors..
=> Basic view creations

app/views/posts/show.html.erb, app/views/shared/_navbar.html.erb
just added a link to homepage when you click on verifi
=> added link to navbar to homepage

Gemfile, app/controllers/image_results_controller.rb, db/migrate/20230524035325_add_columns_to_image_result_table.rb, db/schema.rb
need more testing before i can know it if really works
=> Api foundations

Gemfile.lock, app/controllers/image_results_controller.rb, app/views/image_results/index.html.erb, app/views/image_results/show.html.erb
=> Api testing

Gemfile, app/controllers/image_results_controller.rb
=> all is good

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb
need to be old enough and can now create a username on account creation
=> user must be 18 and can now create a username

app/controllers/posts_controller.rb, app/models/post.rb, app/views/posts/edit.html.erb, app/views/posts/show.html.erb
=> fixed the bugs in the edit and delete buttons

app/views/posts/show.html.erb
=> deleted end

app/policies/post_policy.rb
the policy was wrong so I fixed that...
i also added a def index? which i am 99% sure is unecessary, but I added so I would remember what I changed
=> fixed the posts so now everyone can see every post

app/controllers/image_results_controller.rb, app/views/image_results/show.html.erb, db/migrate/20230525023927_add_text_columns_to_image_results_model.rb, db/schema.rb
=> added profanity to the results

app/assets/config/manifest.js, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_index.scss, app/models/post.rb, app/views/posts/index.html.erb, config/initializers/acts_as_taggable_on.rb
-Advanced search through tag_list(tag names) on the posts index page
-Comma-separated category search on the posts index page
- Minor fix in staying on the posts index page
=> Advanced category

app/assets/stylesheets/components/_index.scss, app/controllers/image_results_controller.rb, app/views/image_results/new.html.erb, app/views/image_results/show.html.erb, app/views/posts/new.html.erb, app/views/posts/show.html.erb
added some HTML and CSS to the image-results new page to make it look more pleasing to the eye
=> CSS for image-restults new

app/controllers/comments_controller.rb, app/controllers/posts_controller.rb, app/models/notification.rb, app/models/post.rb, app/models/user.rb, app/views/shared/_navbar.html.erb, db/migrate/20230525035246_create_notifications.rb, db/schema.rb, test/controllers/notifications_controller_test.rb, test/models/notification_test.rb
users are notified when a new comment is made on their post
=> wow this was a pain but finally got it working

app/controllers/image_results_controller.rb, app/views/image_results/index.html.erb, app/views/image_results/show.html.erb
added delete button to Results page. 
*deleted an 's'  ImageResultsController, there was an xtra S on a result, so the code was broken
*I added 'authorize @result' to the destroy method
=> Added delete button to results page

app/views/image_results/index.html.erb, db/schema.rb
=> added margin

app/models/user.rb, app/views/posts/index.html.erb, app/views/posts/show.html.erb
jusr changed the default avatar to be not some random lady
=> avatars changed

Gemfile, Gemfile.lock, app/views/image_results/show.html.erb, app/views/pages/tips.html.erb, config/initializers/rails_admin.rb, config/routes.rb, db/migrate/20230523044216_add_admin_to_users.rb, db/schema.rb
MAKE SURE TO 
bundle install
rails g rails_admin:install
=> added admin to our app

Gemfile, app/models/post.rb, app/models/user.rb, db/seeds.rb
you will need to run
rails db:seed
=> Better seeds

Gemfile, app/assets/stylesheets/components/_post_card.scss, app/views/image_results/index.html.erb
- Added styling to the my page (grid look)
=> added styling to the mypage

app/assets/stylesheets/components/_post_card.scss, app/assets/stylesheets/components/comment_card.css, app/assets/stylesheets/components/comment_card.css.map, app/assets/stylesheets/components/results_container.css, app/assets/stylesheets/components/results_container.css.map, app/views/image_results/index.html.erb
-fixed the css component issue. Post-card components were used for multiple purposes but now seperated.
=> fixed css component conflict

app/controllers/image_results_controller.rb, app/helpers/image_results_helper.rb, config/initializers/chartkick.rb
graphs cahnge color based on value
=> colors workkkk

app/controllers/image_results_controller.rb, app/views/image_results/show.html.erb
now has a bit more explanation about graph
=> messages display with results

app/views/image_results/show.html.erb
added styling to the image result page
=> Stylingresult

app/views/image_results/show.html.erb
=> fixed conflicts

Gemfile.lock, app/views/posts/show.html.erb
Moved the edit and delete button up and changed them into icons
=> Verifi fixes

app/views/image_results/index.html.erb, app/views/image_results/show.html.erb
"back to results" on results page changed to "my results"
option to verifi another image added on results
my results ordered by most recent
=> minor issues fix

app/controllers/image_results_controller.rb, app/views/image_results/show.html.erb
added drop down for more information on each category on results page, works but needs styling
=> drop down finished

Gemfile.lock, app/controllers/image_results_controller.rb, app/models/cell.rb
added .to_f to the Cell model on sexual_activity, gore, etc.
=> Create cell fix

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_post_card.scss, app/controllers/image_results_controller.rb, app/models/image_result.rb, app/views/image_results/index.html.erb, app/views/image_results/show.html.erb
- added image_result status to the index page(my results page)
=> Image_result status to the index page (My results page)

app/views/shared/_bottom_navbar.html.erb
Added styling on bottom nav for multiple devices
=> added styling on bottom nav for multiple devices

Gemfile.lock, app/controllers/image_results_controller.rb, app/views/posts/new.html.erb
=> Removed suggestive to make API more accurate 

Gemfile.lock, app/views/posts/new.html.erb
took away image upload on new post in community
=> takeaway image upload on community

app/views/image_results/show.html.erb
Added styling to the result page
=> added styling to the result page

app/views/image_results/show.html.erb
not needed because my results button is on navbar
=> rmoved my results button on my results show page 

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_post_card.scss, app/assets/stylesheets/components/_result.scss, app/views/image_results/index.html.erb
- updated styling to the results page with refined cards
=> updating styling to results page

app/assets/stylesheets/components/_home_card.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb, config/routes.rb
removed picture and changed the text a tiny bit on the home page
=> Cosmetic changes

Gemfile.lock, app/assets/stylesheets/components/_gridcell.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_loadingjs.scss, app/javascript/controllers/index.js, app/javascript/controllers/typed_controller.js, app/views/image_results/show.html.erb
=> added styling to danger box on cell, also basic loading screen typing screen 

app/views/pages/home.html.erb, public/404.html, public/422.html, public/500.html
changed content and colors a bit
=> error pages have customized colors and messages now

app/controllers/cells_controller.rb, app/controllers/image_results_controller.rb, config/environments/production.rb
there should NOT be decimals in the url I guess
=> grid is fine again

app/controllers/cells_controller.rb
we added a manual validation step to see if that helps
=> need to test on heroku

app/controllers/cells_controller.rb
Reverts garveyanne/verifi.social#121
the test did not work
=> Revert "need to test on heroku"

app/views/image_results/<div class="container" data-controller=".erb, app/views/image_results/<div class="container" data-controller=".html, app/views/image_results/show.html.erb, db/migrate/20230601044316_add_index_to_cells.rb, db/schema.rb
Reverts garveyanne/verifi.social#123
=> Revert "Grid rep"

app/controllers/cells_controller.rb, db/migrate/20230601052712_add_index_to_cells.rb, db/schema.rb
=> lets seeee

app/assets/stylesheets/components/_icon.scss, app/assets/stylesheets/components/_index.scss, app/views/image_results/show.html.erb
- adjusted space between icons on image-result show page
=> adjusted space between icons

app/assets/stylesheets/components/_index.scss, app/javascript/controllers/typed_controller.js, app/views/image_results/show.html.erb
=> fixed javascript typed.js it now works

app/assets/stylesheets/components/_icon.scss, app/views/image_results/show.html.erb
=> adjusted icon style

app/assets/stylesheets/components/_results_card.scss, app/views/image_results/show.html.erb
graph now shows only if danger or caution. 
fixed the rounded image on breakdown images
=> Results image round

app/assets/stylesheets/components/_results_card.scss, app/views/image_results/show.html.erb, db/schema.rb
UNrounded images for the breakdown image
=> hopefully unrounded the image on breakdown

app/views/image_results/show.html.erb
fixed the issues with the risk alerts, changed the if statements
=> fixed the risk alert errors

app/views/image_results/show.html.erb
needed to change an unless statment
=> image displays on initial show now

app/assets/stylesheets/components/_icon.scss, app/views/image_results/show.html.erb
- replaced svg icon with font-awesome icon
=> Iconreplace

app/views/image_results/show.html.erb
adjusted margin to mt-2 on results pages. to evenly space the divs
=> adjusted marjin between divs on restuls page

app/views/image_results/show.html.erb
- removed a border on the annotations 
- adjusted margin on the show result page
=> Margin on show result page and Border on the annotations 

app/assets/stylesheets/components/_bottom_navbar.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_bottom_navbar.html.erb
Adjusted icon posotions so that it looks optimal on PWA view
=> Adjusted icon posotions so that it looks optimal on PWA view

app/views/image_results/show.html.erb
rearranged risk order so that high and cation will show
=> rearranged risk order so that high and cation will show

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_home_card.scss, app/views/pages/home.html.erb
NO PUSH TO HEROKU IS NEEDED UNTIL WE FINISH THE DEMO!
- added styling for the home page on the desktop environment
=> added stylign for home page on desktop view

app/views/image_results/show.html.erb
- added margin to the result page
- button text fixed
=> fixed margin on the result page

app/views/image_results/new.html.erb
=> changed the button text
